name: Build artifact

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  update-code:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Deploy new version
        run: |
            cd /home/dspace/AntarCris-frontend
            git pull origin main


  build-new-version:
    needs: update-code
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build prod
        run: |
            cd /home/dspace/AntarCris-frontend
            export NODE_OPTIONS=--max-old-space-size=4096
            yarn build:prod
            cp -rf /home/dspace/AntarCris-frontend/dist /home/dspace/dspace-ui


  reload-nodes:
    needs: build-new-version
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Reload PM2 nodes
        run: |
            cd /home/dspace/dspace-ui
            pm2 reload dspace-ui.json --env production

